In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt



#### This is code to See your Visualization Within your Jupyter Notebokk
### Code source is 
[click](https://github.com/machinelearning147/MachineLearning-YouTube/blob/master/src/Visualizing%20TensorFlow%20Graphs.ipynb)

In [2]:
import numpy as np
from IPython.display import clear_output, Image, display, HTML

def strip_consts(graph_def, max_const_size=32):
    """Strip large constant values from graph_def."""
    strip_def = tf.GraphDef()
    for n0 in graph_def.node:
        n = strip_def.node.add() 
        n.MergeFrom(n0)
        if n.op == 'Const':
            tensor = n.attr['value'].tensor
            size = len(tensor.tensor_content)
            if size > max_const_size:
                tensor.tensor_content = "<stripped %d bytes>"%size
    return strip_def

def show_graph(graph_def, max_const_size=32):
    """Visualize TensorFlow graph."""
    if hasattr(graph_def, 'as_graph_def'):
        graph_def = graph_def.as_graph_def()
    strip_def = strip_consts(graph_def, max_const_size=max_const_size)
    code = """
        <script src="//cdnjs.cloudflare.com/ajax/libs/polymer/0.3.3/platform.js"></script>
        <script>
          function load() {{
            document.getElementById("{id}").pbtxt = {data};
          }}
        </script>
        <link rel="import" href="https://tensorboard.appspot.com/tf-graph-basic.build.html" onload=load()>
        <div style="height:600px">
          <tf-graph-basic id="{id}"></tf-graph-basic>
        </div>
    """.format(data=repr(str(strip_def)), id='graph'+str(np.random.rand()))

    iframe = """
        <iframe seamless style="width:1200px;height:620px;border:0" srcdoc="{}"></iframe>
    """.format(code.replace('"', '&quot;'))
    display(HTML(iframe))

In [5]:
## Check Version of your Tensorflow
display("Tensorflow version is" + (tf.__version__))


'Tensorflow version is1.8.0'

In [7]:
pwd  ## To check you current Working Directory

'H:\\Tensorflow-101'

### Building, Running, and Visualizing The tensorflow Model 
#### To access full Tutorial 
[click](https://app.pluralsight.com/library/courses/tensorflow-understanding-foundations/table-of-contents)


In [13]:
g = tf.Graph()      ## Initialize a graph 
with g.as_default():
    
    ### Let's define some constant

    a = tf.constant(6 , name = 'constant_a')
    b = tf.constant(3 , name = 'constant_b')
    c = tf.constant(10 , name = 'constant_c')
    d = tf.constant(5 , name = 'constant_d')

    ## Create Some operations on them

    mul = tf.multiply(a ,b  ,name='mul')
    div = tf.div(c, d ,name='div')
    addn = tf.add_n([mul ,div] , name='addn')
    

### All these steps constructed A graph in tf  but it is not executed yet

#### Running and graph

#### To get Actual values of computation we have to run the graph that is build 
#### In tensorflow first we built a graph then run it on multiple instances

### We run tf.Session to make sesson object which will spervise whole process of execution

In [10]:
sess = tf.Session()

In [11]:
display(sess.run(addn))
display(sess.run(mul))
display(sess.run(div))


20

18

2

### We can call seeson to run on node and graph will run only till that node not beyond that node

In [16]:
tf.summary.FileWriter("logs", g).close()  ## Open the graph
show_graph(g) ## By running function and closing it simultainiously
sess.close()
### Close the session its good habit

In [21]:
g = tf.Graph()      ## Initialize a graph 
with g.as_default():
    
    ## Define Some constant
    
    a = tf.constant(6.5 , name = "constant_a")
    b = tf.constant(3.4 , name = "constant_b")
    c = tf.constant(3.0 , name = "constant_c")
    d = tf.constant(100.2 , name = "constant_d")
    
    ##Do some calculations on them 
    
    square = tf.square(a , name = 'square_a')
    power = tf.pow(b,c,name = "pow_b_c")
    sqrt = tf.sqrt(d,name = 'sqrt_d')
    final_sum = tf.add_n([square , power , sqrt] , name = 'final_sum')
    another_sum = tf.add_n([a,b,c,d,power] , name='another')
    sess = tf.Session()
    

### There are many more mathe operation are there explore them in Tensorflow documentation

In [22]:
display(sess.run(square))
display(sess.run(power))
display(sess.run(sqrt))
display(sess.run(final_sum))

42.25

39.304005

10.009995

91.563995

In [23]:
tf.summary.FileWriter("logs", g).close()  ## Open the graph
show_graph(g) ## By running function and closing it simultainiously
sess.close()

### Rank of tensor 


In [24]:
sess = tf.Session()
Zerod =  tf.constant(5)

In [25]:
sess.run(tf.rank(Zerod))

0

In [26]:
oneD = tf.constant(['How' , 'are'  , 'you'])
sess.run(tf.rank(oneD))

1

In [29]:
twoD =  tf.constant([[1.0 , 2.3] , [1.5,2.9]])
sess.run(tf.rank(twoD))

### So we can extend to n-dimension

2

## Let's Explore some more mathematical operation on tensors

In [30]:
g = tf.Graph()

with g.as_default():

    x = tf.constant([100,200,300] , name='x')
    y = tf.constant([1,2,3] , name='y')
    sum_x = tf.reduce_sum(x , name ='sum_x')
    prod_y  =tf.reduce_prod(y , name='prod_y')

    final_div = tf.div(sum_x , prod_y , name = 'final_div')
    final_mean = tf.reduce_mean([sum_x , prod_y] ,name ="final_mean")

    sess = tf.Session()

In [31]:
display(sess.run(x))
display(sess.run(y))
display(sess.run(sum_x))
display(sess.run(prod_y))
display(sess.run(final_div))
display(sess.run(final_mean))

array([100, 200, 300])

array([1, 2, 3])

600

6

100

303

In [32]:
tf.summary.FileWriter("logs", g).close()  ## Open the graph
show_graph(g) ## By running function and closing it simultainiously
sess.close()

In [33]:
import numpy as np

#### Tensorflow is perfectly Compatible with NumPy

#### Numpy Araays can be treated as tensors
###  np.int32 == tf.int32

In [35]:
sess = tf.Session()
zeroD = np.array(30 ,dtype=np.int32)
oneD = np.array([5.6,2.2,3.2,9.0] , dtype=np.float32)

In [36]:
display(sess.run(tf.rank(zeroD)))
display(sess.run(tf.shape(zeroD)))
display(sess.run(tf.rank(oneD)))
display(sess.run(tf.shape(oneD)))

0

array([], dtype=int32)

1

array([4])

### Tensor are n-dimensional array